[package]
name = "leptos_hotkeys"
version = "0.1.0"
edition = "2021"
authors=["Matthew Kim", "Robert Junkins"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.5.4", features = ["csr", "nightly"] }
wasm-bindgen = "0.2.89"
log = "0.4.20"

# needed for macro exports
[lib]
name = "leptos_hotkeys"
path = "src/lib.rs"
